//
// Created by jsoar on 6/13/2026.
//

#pragma once
#include <expected>
#include <optional>
#include <string>

template<typename T>
using Result = std::expected<T, std::string>;

template<typename T>
using Option = std::optional<T>;
#define None std::nullopt

#define ERROR_HANDLING_CONCAT_IMPL(X, Y) X##Y
#define ERROR_HANDLING_CONCAT(X, Y) ERROR_HANDLING_CONCAT_IMPL(X, Y)
#define ERROR_HANDLING_UNIQUE_NAME(Name) ERROR_HANDLING_CONCAT(AutoGenerated_##Name, __LINE__)

// These are poor man's approximations of Rust's ? operator. If a function returning a std::expected or std::optional returns an error/nullopt, immediately return it from the current function.
// TRY_ASSIGN can be used to extract the value and place it in a variable. Unfortunately this cannot be done directly for const variables without leaking the temporary result type into the enclosing scope.
#define TRY(Call) { auto ERROR_HANDLING_UNIQUE_NAME(Result) = Call; if(!ERROR_HANDLING_UNIQUE_NAME(Result).has_value()) { FAIL(ERROR_HANDLING_UNIQUE_NAME(Result).error()); }}
#define TRY_ASSIGN(Output, Call) { auto ERROR_HANDLING_UNIQUE_NAME(Result) = Call; if(!ERROR_HANDLING_UNIQUE_NAME(Result).has_value()) { FAIL(ERROR_HANDLING_UNIQUE_NAME(Result).error()); } Output = std::move(ERROR_HANDLING_UNIQUE_NAME(Result)).value(); }
#define TRY_CONSTRUCT(Output, Call)  auto ERROR_HANDLING_UNIQUE_NAME(Result) = Call; if(!ERROR_HANDLING_UNIQUE_NAME(Result).has_value()) { FAIL(ERROR_HANDLING_UNIQUE_NAME(Result).error()); } Output = std::move(ERROR_HANDLING_UNIQUE_NAME(Result)).value()

// Syntactic sugar for returning errors
#define FAIL(Err) return std::unexpected { Err }